# This is a basic workflow to help you get started with Actions

name: Compile Latex

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  latex-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: Sakul6499/GitHub-Action-LaTeX@v1.0.0
        with:
          latex_main_file: main.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
